# BADGE LIST CONFIGURATION FILE

defaults: &defaults
  # Page sizes should be evenly divisible by 2 and 3 (4 is nice but not required)
  page_size_small: 12
  page_size_normal: 36
  page_size_large: 72
  
  # API constants
  max_import_list_size: 500

  # SUBSCRIPTION FEATURES
  # Adding features here makes them appear in the subscription details panel. But when adding new features also add manual granting fields
  # to group model (search for `feature_grant_`), group form and groups controller permitted params. Also add feature to the pricing page.
  # You will also need to run the `refresh_group_subscription_features` rake task in production.
  feature_details:
    community:
      label: Community Badges & Wiki
      description: Includes unlimited badge awarders and community wiki pages
    reporting:
      label: Reporting
      description: Admins are able to export group activity to CSV
    bulk_tools:
      label: Bulk Tools
      description: Allows badges to be awarded in bulk via CSV or manually built lists
    integration:
      label: Third-Party Integrations
      description: Includes access to LTI integration and all future integrations

  # Subscription Plans
  subscription_plans:
    standard:
      solo-1m-2:
        name: Solo
        amount: 1000
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Solo
        icon: fa-user
        color: blue
        description: |
          1 admin / badge awarder
        users: 5000
        admins: 1
        sub_groups: 0
        features: []
      solo-1y-1:
        name: Solo Annual
        amount: 11000
        currency: usd
        interval: year
        trial_period_days: 0
        statement_descriptor: Badge List Solo
        icon: fa-user
        color: blue
        description: |
          1 admin / badge awarder
        users: 5000
        admins: 1
        sub_groups: 0
        features: []
      team-1m-1:
        name: Team
        amount: 3000
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Team
        icon: fa-users
        color: green
        description: |
          3 admins, unlimited badge awarders
        users: 5000
        admins: 3
        sub_groups: 0
        features:
        - community
      team-1y-1:
        name: Team Annual
        amount: 33000
        currency: usd
        interval: year
        trial_period_days: 0
        statement_descriptor: Badge List Team
        icon: fa-users
        color: green
        description: |
          3 admins, unlimited badge awarders
        users: 5000
        admins: 3
        sub_groups: 0
        features:
        - community
      org-1m-1:
        name: Org
        amount: 13000
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Org
        icon: fa-building
        color: orange
        description: |
          Unlimited admins &amp; badge awarders, reporting, bulk tools, integrations
        users: 5000
        admins: -1
        sub_groups: 5
        sub_group_amount: 1000
        features:
        - community
        - reporting
        - bulk_tools
        - integration
      org-1y-1:
        name: Org Annual
        amount: 143000
        currency: usd
        interval: year
        trial_period_days: 0
        statement_descriptor: Badge List Org
        icon: fa-building
        color: orange
        description: |
          Unlimited admins &amp; badge awarders, reporting, bulk tools, integrations
        users: 5000
        admins: -1
        sub_groups: 5
        sub_group_amount: 1000
        features:
        - community
        - reporting
        - bulk_tools
        - integration
    k12:
      k12-teacher-1y-1:
        name: K12 Teacher Annual
        amount: 2500
        currency: usd
        interval: year
        trial_period_days: 0
        statement_descriptor: Badge List K12 Teacher
        icon: fa-user
        color: blue
        description: |
          1 teacher, annual billing only
        users: 5000
        admins: 1
        sub_groups: 0
        features: []
      k12-school-1m-1:
        name: K12 School
        amount: 6500
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List K12 School
        icon: fa-building
        color: orange
        description: |
          Unlimited admins &amp; badge awarders, reporting, bulk tools, integrations
        users: 5000
        admins: -1
        sub_groups: 5
        sub_group_amount: 500
        features:
        - community
        - reporting
        - bulk_tools
        - integration
      k12-school-1y-2:
        name: K12 School Annual
        amount: 70000
        currency: usd
        interval: year
        trial_period_days: 0
        statement_descriptor: Badge List K12 School
        icon: fa-building
        color: orange
        description: |
          Unlimited admins &amp; badge awarders, reporting, bulk tools, integrations
          (Includes discount for annual billing)
        users: 5000
        admins: -1
        sub_groups: 5
        sub_group_amount: 500
        features:
        - community
        - reporting
        - bulk_tools
        - integration
    internal:
      solo-free-1:
        name: Enterprise Solo
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Enterprise
        icon: fa-star
        description: |
          Badge List Enterprise
        users: 5000
        admins: 1
        sub_groups: 0
        features: []
      team-free-1:
        name: Enterprise Team
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Enterprise
        icon: fa-star
        description: |
          Badge List Enterprise
        users: 5000
        admins: 3
        sub_groups: 0
        features:
        - community
      org-free-1:
        name: Enterprise Org
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Enterprise
        icon: fa-star
        description: |
          Badge List Enterprise
        users: 5000
        admins: 3
        sub_groups: 5
        sub_group_amount: 0
        features:
        - community
        - reporting
        - bulk_tools
        - integration
    test:
      test-100d-1:
        name: Daily 100
        amount: 200
        currency: usd
        interval: day
        trial_period_days: 0
        statement_descriptor: Badge List Daily 100
        icon: fa-star
        description: |
          Badge List Daily 100
        users: 100
        admins: -1
        sub_groups: 0
        features:
        - community
      test-100d-1t:
        name: Daily 100 with Trial
        amount: 200
        currency: usd
        interval: day
        trial_period_days: 1
        statement_descriptor: Badge List Daily 100
        icon: fa-star
        description: |
          Badge List Daily 100
          Badge List Daily 100
        users: 100
        admins: -1
        sub_groups: 0
        features:
        - community
    retired:
      solo-1m-1:
        name: Solo (Legacy)
        amount: 500
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Solo
        icon: fa-user
        description: |
          1 admin / badge awarder
        users: 5000
        admins: 1
        sub_groups: 0
        features: []
      k12-team-1m-1:
        name: K12 Team (Legacy)
        amount: 1500
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List K12 Team
        icon: fa-users
        description: |
          3 admins, unlimited badge awarders
        users: 5000
        admins: 3
        sub_groups: 0
        features:
        - community
      k12-team-1y-1:
        name: K12 Team Annual (Legacy)
        amount: 12000
        currency: usd
        interval: year
        trial_period_days: 0
        statement_descriptor: Badge List K12 Team
        icon: fa-users
        description: |
          3 admins, unlimited badge awarders
          (Includes discount for annual billing)
        users: 5000
        admins: 3
        sub_groups: 0
        features:
        - community
      k12-school-1y-1:
        name: K12 School Annual (Legacy)
        amount: 48000
        currency: usd
        interval: year
        trial_period_days: 0
        statement_descriptor: Badge List K12 School
        icon: fa-building
        description: |
          Unlimited admins &amp; badge awarders, reporting, bulk tools, integrations
          (Includes discount for annual billing)
        users: 5000
        admins: -1
        sub_groups: 5
        sub_group_amount: 500
        features:
        - community
        - reporting
        - bulk_tools
        - integration
      standard-100m-1:
        name: Starter
        amount: 5000
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Starter
        users: 100
        admins: -1
        sub_groups: 0
        features: []
      standard-500m-1:
        name: Basic
        amount: 12000
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Basic
        users: 500
        admins: -1
        sub_groups: 1
        features: []
      standard-1000m-1:
        name: Standard
        amount: 20000
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Standard
        users: 1000
        admins: -1
        sub_groups: 5
        features: []
      standard-5000m-1:
        name: Premium
        amount: 45000
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Premium
        users: 5000
        admins: -1
        sub_groups: -1
        features: []
      k12-1y-1:
        name: Single Teacher
        amount: 2500
        currency: usd
        interval: year
        trial_period_days: 0
        statement_descriptor: Badge List K12 Teacher
        users: 5000
        admins: 1
        sub_groups: 0
        features: []
      free-5m-1:
        name: Free Mini
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Free
        users: 5
        admins: -1
        sub_groups: -1
        features: []
      free-100m-1:
        name: Free Starter
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Free
        users: 100
        admins: -1
        sub_groups: 0
        features: []
      free-500m-1:
        name: Free Basic
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Free
        users: 500
        admins: -1
        sub_groups: 1
        features: []
      free-unlimited-1:
        name: Free Unlimited
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Free
        users: -1
        admins: -1
        sub_groups: -1
        features: []
      trial-100m-1:
        name: Trial Starter
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Trial
        users: 100
        admins: -1
        sub_groups: 0
        features: []

  # This controls disallowed values for group & badge urls
  blocked_url_slugs:
   - add
   - admin
   - admins
   - assets
   - badge
   - badges
   - cancel
   - copy_badges
   - create
   - delete
   - destroy
   - domain
   - domains
   - edit
   - entry
   - entries
   - exercise
   - exercises
   - expert
   - experts
   - group
   - groups
   - index
   - invitation
   - invited_admins
   - invited_members
   - join
   - learner
   - learners
   - leave
   - log
   - logs
   - member
   - members
   - move
   - new
   - perm_assets
   - pricing
   - privacy-policy
   - select_badges
   - select_group
   - show
   - support
   - update
   - user
   - users
   - terms-of-service
   - validation
   - validations

  default_badge_info: |
    <h3>Getting started...</h3>
    The badge overview will be the first thing that new visitors to the badge see. 
    You can use it to provide context, give instructions or share links to useful resources.
  
  default_log_wiki: |
    <h3>About me...</h3>
    Tell the badge community a little about yourself.

development:
  <<: *defaults
  from_email: knowledgestreem@gmail.com
  root_url: 'http://localhost:3000'

test:
  <<: *defaults
  from_email: knowledgestreem@gmail.com
  root_url: 'http://localhost:3000'

production:
  <<: *defaults
  from_email: app@badgelist.com
  root_url: 'https://www.badgelist.com'
