# BADGE LIST STANDARD APPS
# 
# This is consumed by the `standard_apps.rb` initializer and contains instances of the App model which will be automatically
# built on app startup.
# 
# For now this only contains the Badge List app itself, but in the future it may contain other first-party data integrations.

#=== BADGE LIST ===#
badgelist:
  name: Badge List
  type: free
  summary: Badge List is a platform for awarding digital badges.
  description: |
    The Badge List app generates activity based on your interaction with the platform.
    Every group that you join automatically has access to all of your Badge List activity within that specific group.
  organization: Badge List
  website: https://www.badgelist.com/docs
  email: team@badgelist.com
  image_url: https://s3.amazonaws.com/badgelist/images/badge-list-icon.png
