# BADGE LIST CONFIGURATION FILE

defaults: &defaults
  # Page sizes should be evenly divisible by 2 and 3 (4 is nice but not required)
  page_size_small: 12
  page_size_normal: 30
  page_size_large: 60

  # This controls disallowed values for group & badge urls
  blocked_url_slugs:
   - add
   - admin
   - admins
   - badge
   - badges
   - create
   - delete
   - destroy
   - edit
   - entry
   - entries
   - exercise
   - exercises
   - expert
   - experts
   - group
   - groups
   - index
   - invitation
   - invited_admins
   - invited_members
   - join
   - learner
   - learners
   - leave
   - log
   - logs
   - member
   - members
   - new
   - show
   - support
   - update
   - user
   - users
   - validation
   - validations

  default_badge_info: |
    <h3>Getting started...</h3>
    The badge overview will be the first thing that new visitors to the badge see. 
    You can use it to provide context, give instructions or share links to useful resources.
  
  default_log_wiki: |
    <h3>About me...</h3>
    Tell the badge community a little about yourself.

development:
  <<: *defaults
  from_email: knowledgestreem@gmail.com

test:
  <<: *defaults
  from_email: knowledgestreem@gmail.com

production:
  <<: *defaults
  from_email: app@badgelist.com
