# BADGE LIST CONFIGURATION FILE

defaults: &defaults
  page_size: 28

  # This controls disallowed values for group & badge urls
  blocked_url_slugs:
   - about
   - add
   - admin
   - admins
   - badge
   - badges
   - contact
   - delete
   - destroy
   - edit
   - expert
   - experts
   - group
   - groups
   - help
   - index
   - invitation
   - invited_admins
   - invited_members
   - learner
   - learners
   - leave
   - log
   - logs
   - member
   - members
   - new
   - show
   - support
   - update
   - user
   - users

  default_badge_info: |
    <h3>Overview</h3><br>
    Use this area to store information and instructions that will be useful to badge learners
    and experts. Also remember to include information that will be relevant to the public when
    they refer to the badge at a later date.<br><br>
    <strong>Use Lists to Suggest Pathways</strong><br>
    <ul><li>#intro - Use hashtags to create wiki pages</li>
    <li>#resources - Hashtags can also be used in learners' log entries</li></ul>
    -----<br>
    <h3>Formatting Examples</h3>
    <strong>Section Breaks:</strong><br>
    Create section breaks by including one or more dashes on a separate line.<br><br>
    <strong>Links:</strong><br>
    #hash-tags are automatically made #clickable, #Use_Them_Freely.<br>
    URLs are also made clickable: http://en.wikipedia.org/wiki/Open-source_software<br><br>
    <strong>Images:</strong><br>
    URLs with image extensions will automatically be turned into embedded images or you can 
    add an "img:" prefix for links that aren't automatically recognized.<br>
    img:http://bit.ly/1l4vkp4

  default_log_wiki: |
    I'm new here.<br>
    -----<br>
    I haven't added any information to my wiki yet.

development:
  <<: *defaults
  from_email: knowledgestreem@gmail.com

test:
  <<: *defaults
  from_email: knowledgestreem@gmail.com

production:
  <<: *defaults
  from_email: app@badgelist.com
