# BADGE LIST CONFIGURATION FILE

defaults: &defaults
  # Page sizes should be evenly divisible by 2 and 3 (4 is nice but not required)
  page_size_small: 12
  page_size_normal: 30
  page_size_large: 60

  # Subscription Plans
  subscription_plans:
    standard:
      standard-100m-1:
        name: Starter
        amount: 5000
        currency: usd
        interval: month
        trial_period_days: 14
        statement_descriptor: Badge List Starter
        users: 100
        admins: -1
        sub_groups: 0
      standard-500m-1:
        name: Basic
        amount: 12000
        currency: usd
        interval: month
        trial_period_days: 14
        statement_descriptor: Badge List Basic
        users: 500
        admins: -1
        sub_groups: 1
      standard-1000m-1:
        name: Standard
        amount: 20000
        currency: usd
        interval: month
        trial_period_days: 14
        statement_descriptor: Badge List Standard
        users: 1000
        admins: -1
        sub_groups: 5
      standard-5000m-1:
        name: Premium
        amount: 45000
        currency: usd
        interval: month
        trial_period_days: 14
        statement_descriptor: Badge List Premium
        users: 5000
        admins: -1
        sub_groups: -1
    k12:
      k12-1y-1:
        name: Single Teacher
        amount: 2500
        currency: usd
        interval: year
        trial_period_days: 14
        statement_descriptor: Badge List K12 Teacher
        users: -1
        admins: 1
        sub_groups: 0
    free:
      free-5m-1:
        name: Free Mini
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Free
        users: 5
        admins: -1
        sub_groups: -1
      free-100m-1:
        name: Free Starter
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Free
        users: 100
        admins: -1
        sub_groups: 0
      free-500m-1:
        name: Free Basic
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Free
        users: 500
        admins: -1
        sub_groups: 1
      free-unlimited-1:
        name: Free Unlimited
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Free
        users: -1
        admins: -1
        sub_groups: -1
    trial:
      trial-100m-1:
        name: Trial Starter
        amount: 0
        currency: usd
        interval: month
        trial_period_days: 0
        statement_descriptor: Badge List Trial
        users: 100
        admins: -1
        sub_groups: 0
    test:
      test-100d-1:
        name: Daily 100
        amount: 200
        currency: usd
        interval: day
        trial_period_days: 0
        statement_descriptor: Badge List Daily 100
        users: 100
        admins: -1
        sub_groups: 0
      test-100d-1t:
        name: Daily 100 with Trial
        amount: 200
        currency: usd
        interval: day
        trial_period_days: 1
        statement_descriptor: Badge List Daily 100
        users: 100
        admins: -1
        sub_groups: 0

  # This controls disallowed values for group & badge urls
  blocked_url_slugs:
   - add
   - admin
   - admins
   - assets
   - badge
   - badges
   - cancel
   - create
   - delete
   - destroy
   - edit
   - entry
   - entries
   - exercise
   - exercises
   - expert
   - experts
   - group
   - groups
   - index
   - invitation
   - invited_admins
   - invited_members
   - join
   - learner
   - learners
   - leave
   - log
   - logs
   - member
   - members
   - move
   - new
   - perm_assets
   - pricing
   - privacy-policy
   - show
   - support
   - update
   - user
   - users
   - terms-of-service
   - validation
   - validations

  default_badge_info: |
    <h3>Getting started...</h3>
    The badge overview will be the first thing that new visitors to the badge see. 
    You can use it to provide context, give instructions or share links to useful resources.
  
  default_log_wiki: |
    <h3>About me...</h3>
    Tell the badge community a little about yourself.

development:
  <<: *defaults
  from_email: knowledgestreem@gmail.com
  root_url: 'http://localhost:3000'

test:
  <<: *defaults
  from_email: knowledgestreem@gmail.com
  root_url: 'http://localhost:3000'

production:
  <<: *defaults
  from_email: app@badgelist.com
  root_url: 'http://www.badgelist.com'
