# EXAMPLE DATA FOR sample_data.rake

badge_image_urls:
 - "http://a1.distilledcdn.com/wp-content/uploads/2012/03/excel-badge.png"
 - "http://mattersofgrey.com/wp-content/uploads/2010/11/bravo_top_chef_big.png"
 - "http://www.leanteen.com/file/pic/badge/2013/04/ede7ab02976755991fb69412c7860aa5.png"
 - "http://upload.wikimedia.org/wikipedia/en/8/87/Kuk_sool_won_logo.png"
 - "http://teens.denverlibrary.org/sites/teens/files/gamedesign.png"
 - "http://foursquareguru.com/media/badges/moma_big.png"
 - "http://iconbug.com/data/f3/256/600fff96f94015434f9371d881630203.png"
 - "https://wac.a8b5.edgecastcdn.net/80A8B5/badges/badges_iPhone_BlogReader_Stage4.png"
 - "http://www.dallasmuseumofart.org/idc/groups/web_view/documents/dma_images/dma_517998.png"
 - "https://badge.chicagosummeroflearning.org/badge/image/math-by-design.png"
 - "http://s3.amazonaws.com/commendablekids.com.prod/badges/45/large.png?1287262798"
 - "http://tantek.com/presentations/2011/10/html5-now/HTML5_Badge_512.png"
 - "http://www.textually.org/textually/archives/2010/11/25/Baggage%20Handler%20badge.png"
 - "https://wac.a8b5.edgecastcdn.net/80A8B5/badges/badges_eCommerce_Stage1.png"
 - "http://24.media.tumblr.com/48052bc0427c0c48a1a3f0777b0ff6d6/tumblr_mjyumk4gbK1rha3vbo1_500.png"
 - "http://31.media.tumblr.com/8ef0864859850a8594b3cf4271835688/tumblr_mg7kdnpbD71rha3vbo1_500.png"
 - "https://wac.a8b5.edgecastcdn.net/80A8B5/badges/badges_iPhone_CrystalBall_Stage6.png"
 - "https://wac.a8b5.edgecastcdn.net/80A8B5/badges/badges_eCommerce_Stage2.png"
 - "https://wac.a8b5.edgecastcdn.net/80A8B5/badges/badges_DD_Database_Stage2.png"

tags:
 - "#history"
 - "#approaches"
 - "#PRINCE2"
 - "#PROMPT"
 - "#CriticalChain"
 - "#eventchain"
 - "#process-based"
 - "#agile"
 - "#lean"
 - "#extreme_pm"
 - "#benefits-realization"
 - "#processes"
 - "#initiating"
 - "#planning-and-design"
 - "#executing"
 - "#monitoring"
 - "#controlling"
 - "#closing"
 - "#ControlSystems"
 - "#Topics"
 - "#project_managers"
 - "#pmtypes"
 - "#pmtriangle"
 - "#WorkBreakdown"
 - "#pm-framework"
 - "#standards"
 - "#portfoliomgmt"
 - "#pmsoftware"
 - "#VirtualPM"
 - "#construction"
 - "#engineering"
 - "#waterfall"
 - "#delivery"
 - "#methodologies"
 - "#scrum"
 - "#kanban"
 - "#bootcamp"
 - "#financial-analysis"
 - "#budgeting"
 - "#stakeholder-analysis"
 - "#estimation"
 - "#qualityassurance"
 - "#deliverables"
 - "#error_correction"
 - "#usersupport"
 - "#scoping"
 - "#contracts"
 - "#cost-benefit"
 - "#risk"
 - "#TimeManagement"
 - "#technology"
 - "#scope"
 - "#time"
 - "#cost"
 - "#V-Model"
 - "#TSP"
 - "#TotalCostManagement"
 - "#excel"
 - "#HERMES"
 - "#iso9000"

image_urls:
 - "http://www.pimconstructions.com/sites/default/files/Project_management.png"
 - "http://switchbd.com/web/images/sb/pm.jpg"
 - "http://www.solveitbahamas.com/images/project-management.jpg"
 - "http://lillianpierson.com/Blog/wp-content/uploads/2013/12/project-managment-in-crisis-response.jpg"
 - "http://pmpimp.com/wp-content/uploads/2012/07/5921913_ac83ed27bd.jpg"
 - "http://soft.sptechs.com/iimages/34600.gif"
 - "http://www.evengreentechnology.com/sites/www.evengreentechnology.com/files/u13/project-management.jpg"
 - "http://www.phoenixts.com/wp-content/uploads/2013/09/project-management-certification-career-path.png"
 - "http://sempai.fujitsucanada.com/fileadmin/img/Autres/Project_Management_Learning_Path2013.png"
 - "http://www.ppdtraining.com.au/wp-content/uploads/2012/10/projectmanagement3.gif"
 - "http://www.amberplastics.co.uk/UserFiles/Image/project_management.jpg"
 - "http://dlhsoft.com/ProjectManager/Documentation/Screenshots/ProjectManagementConsole.png"
 - "http://upload.wikimedia.org/wikipedia/commons/5/50/Agile_Project_Management_by_Planbox.png"
 - "http://www.agile-training-courses.com/tl_files/images/graphs/agile-project-management2.jpg"
 - "http://www.soundwebsolutions.net/wp-content/uploads/2013/10/aam_diagram.png"
 - "http://www.xqa.com.ar/visualmanagement/wp-content/uploads/Scrumboard_Scrum_of_Scrums_1_small.JPG"
 - "http://lh3.ggpht.com/rbanks54/SEPFKLBrWbI/AAAAAAAAAX4/rCCt2h06StE/IMAG0033_thumb%5B2%5D.jpg"
 - "http://blog.caplin.com/wp-content/uploads/AgileUX-20120215-033a.jpg"
 - "http://public.bn1304.livefilestore.com/y2p_ylNbziIEvzObiikA9SMXIoY58fJmf2DLxJYB_rSgnNAAjR5xTi3dQ5bDkyNrvnbiUMxUeFs7XNYSRWQa9IJzQ/Tasks2.jpg"
 - "http://sbt.blob.core.windows.net/storyboards/examples/users-for-big-company-home-improvement-store.png"
 - "http://theagilepirate.net/wp-content/uploads/scrum_board_full.jpg"
 - "http://blogs.msdn.com/cfs-filesystemfile.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-00-30-15-metablogapi/8625.Figure_2D00_2_5F00_3C2E4853.png"
 - "http://idyeah.com/blog/wp-content/uploads/2012/11/storyboard1-1024x743.png"
 - "http://www.mountaingoatsoftware.com/system/asset/file/33/LabelledTaskBoard.jpg"
 - "https://www.pours.com/IPours/images/Kanban.jpg"
 - "http://www.construsur.net/index.php/files/download/540"
 - "http://4.bp.blogspot.com/--wlDJXuUveA/UbbtEH2alSI/AAAAAAAAIl8/BkrJugSr_A4/s1600/fases_+kanban.jpg"
 - "http://farm3.staticflickr.com/2663/3879260297_dfc867d531_b.jpg"
 - "http://www.intellion.com/fileadmin/user_upload/kanban_en.gif"
 - "http://toolsforagile.com/blog/wp-content/uploads/2013/06/ingredients_of_kanban.jpg"
 - "http://www.bapp.co.uk/wp-content/uploads/2009/04/BAPP-Kanban.jpg"
 - "http://www.handsongroup.com/wp-content/uploads/2012/11/kanban_image4.gif"
 - "http://www.narmco.com/images/kanban-shipping.jpg"
 - "http://api.ning.com/files/h7-hnikYBT3zU9qhe5UIg7DrqCRuBpRMjJS0WZmGQgPtwVUcp2R8B*o1Mfrsk7N17iO*71kWmG2bSpNwvFEuojJz71iqjfp3/C2Kanban.jpg"
 - "http://www.scrumsense.com/wp-content/uploads/2012/11/Kanban.jpg"
 - "http://3.bp.blogspot.com/-KIC5mbfoR84/UUsYk-BAIUI/AAAAAAAAEJc/PIPzaCrYV9U/s1600/Kanban+-+Depth+of+Kanban+Implementation+-+Instructions.png"
 - "http://www.iso.org/iso/iso_survey_hp.jpg"
 - "http://www.envirocentre.ie/includes/images/EMS2.jpg"
 - "http://lerablog.org/wp-content/uploads/2013/05/construction-site.jpg"
 - "http://www.osha10hourtraining.com/wp-content/uploads/construction-site.jpeg"
 - "http://www.carlsonmeissner.com/userfiles/images/construction_workers.jpg"
 - "http://www.omslighting.com/data/images/industry-outdoor-construction-sites.jpg"
 - "http://www.mir.com.my/rb/photography/companies/nikon/nikkoresources/AFNikkor/AF35135mm/construction_site.jpg"
 - "http://static6.businessinsider.com/image/4eea46dbeab8ea913e000011-1200/wtc-construction-site-sep-20.jpg"
 - "http://ej.iop.org/images/0029-5515/52/4/043004/Full/nf398744fig05.jpg"
 - "http://aryaninfrastructure.com/images/Tamarind%20Terrace/Tamarind-terrace-Layout.jpg"
 - "http://2.bp.blogspot.com/-WqE-hLJr4dY/Tgoi4YXcKaI/AAAAAAAAAfs/9DPo48fITpw/s1600/FINAL+layout.jpg"
 - "http://www.mtmconstructionltd.co.uk/images/devs/hatton/hatton-site-plan.jpg"
 - "http://www.bbhomes.co.uk/images/developments/murthly/murthly-plot-map.jpg"
 - "http://www.projects.uts.edu.au/images/diagram2.gif"
 - "http://edge.rit.edu/content/P12401/public/WorkBreakdown.png"
 - "http://consultingblogs.emc.com/Admin/ImageGallery/blogs.conchango.com/Colin.Bird/Scrum%20Overview%20Diagram.png"
 - "http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Scrum.svg/521px-Scrum.svg.png"
 - "http://blogs.independent.co.uk/wp-content/uploads/2011/09/scrum1.jpg"
 - "http://peteyeomans.files.wordpress.com/2012/07/3675547135_7c36ff66f8.jpg"
 - "http://www.kristinsherman.com/wp-content/uploads/2009/08/rugby.jpg"
 - "http://www.nasa.gov/images/content/651411main_jsc2012e052762_full.jpg"
 - "http://assets.inhabitat.com/wp-content/blogs.dir/1/files/2010/12/NASA-Heat-Island-2.jpg"
 - "http://newscenter.lbl.gov/wp-content/uploads/heat-island.jpg"
 - "http://archpaper.com/uploads/image/TempMap3.jpg"
 - "http://www.americaspace.com/wp-content/uploads/2013/01/Bigelow-Aerospace-BEAM-module-posted-on-AmericaSpace.jpg"
 - "http://i.space.com/images/i/000/025/081/i02/bigelow-beam-expandable-space-module-130115c-02.jpg"
 - "http://www.spacenews.com/sites/spacenews.com/files/images/articles/imported//TestStand_NASA02.jpg"
 - "http://1.bp.blogspot.com/-TUSxFKOPm4M/UAnSmODjIoI/AAAAAAAAGzc/BUvklN2ztsE/s1600/Members+of+the+NASA+Hi-C+team+prepare+to+recover+the+telescope+at+White+Sands+Missile+Range+on+July+11,+2012.jpg"
 - "http://nodis3.gsfc.nasa.gov/npg_img/N_PR_8000_004A_/npr8000.4A.C1G5.gif"
 - "http://msis.jsc.nasa.gov/images/Section05/Image158.gif"
 - "http://victoriastaffordapsychicinvestigation.files.wordpress.com/2012/07/the-international-space-station-iss-multilateral-coordination-board-mcbc2a0-nasa-cernan-data-ibrahim-abousawan-airl-team.gif"
 - "http://upload.wikimedia.org/wikipedia/commons/8/8d/NS_Savannah_control_room_MD1.jpg"
 - "http://upload.wikimedia.org/wikipedia/commons/c/ce/Russian_ISS_Flight_Control_Room.jpg"
 - "http://www.hq.nasa.gov/pao/History/SP-4204/images/m363a.jpg"
 - "http://www.collectspace.com/images/news-090313a-lg.jpg"

link_urls:
 - "http://en.wikipedia.org/wiki/Project_management"
 - "http://www.pmi.org/About-Us/About-Us-What-is-Project-Management.aspx"
 - "http://office.microsoft.com/en-us/project-help/a-short-course-in-project-management-HA010235482.aspx"
 - "http://en.wikipedia.org/wiki/David_I._Cleland"
 - "http://www.boozallen.com/about/history/history_5"
 - "http://www.cs.umd.edu/class/spring2003/cmsc838p/Process/waterfall.pdf"
 - "http://webarchive.nationalarchives.gov.uk/20110822131357/http://www.ogc.gov.uk/methods_prince_2__background.asp"
 - "http://support.planbox.com/knowledgebase/topics/34844-agile-project-management-resources"
 - "http://www.oit.va.gov/"
 - "http://en.wikipedia.org/wiki/Harold_Kerzner"
 - "http://cmaanet.org/certified-construction-manager"
 - "http://www.if4it.com/SYNTHESIZED/FRAMEWORKS/PROJECT/project_framework.html"
 - "http://www.pce.uw.edu/certificates/biotechnology-project-management.html"
 - "http://nodis3.gsfc.nasa.gov/displayCA.cfm?Internal_ID=&page_name=&CFID=17601867&CFTOKEN=26457169&jsessionid=f0305589a5cd18f7d00032c7e285c76b3c60"
 - "http://www.techopedia.com/definition/13132/project-management-software"
 - "http://flevy.com/blog/sick-of-microsoft-project-manage-your-project-in-excel/"
 - "http://userwww.sfsu.edu/ceb/b895/btrautsch895.pdf"
 - "http://www.umsl.edu/~sauterv/analysis/488_f01_papers/rolfes.htm"
 - "http://www.amazon.com/The-Virtual-Project-Management-Office-ebook/dp/B005EHQF1M#_"
 - "http://www.pmi.org/en/Knowledge-Center/Research-Completed-Research/Patterns-of-Effective-Project-Management-in-Virtual-Projects.aspx"
 - "http://blog.bootstraptoday.com/2012/04/13/why-you-cannot-avoid-virtual-project-management-2012-onwards/"
 - "http://www.globalknowledge.com/training/course.asp?pageid=9&courseid=10276&catid=196&country=United+States"
 - "http://pm.stackexchange.com/"
 - "http://www.mindtools.com/pages/main/newMN_PPM.htm"
 - "http://www.businessballs.com/project.htm"
 - "https://company.podio.com/project-management-software"
 - "https://basecamp.com/"
 - "http://www.villanovau.com/what-is-project-management/"
 - "http://www.projectmanagement.com/"